kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: default_role
# https://kubernetes.io/docs/reference/access-authn-authz/rbac/
rules:
  - apiGroups: ['']
    resources: ['endpoints', 'secrets', 'services', 'pods']
    verbs: ['get', 'watch', 'list', 'create', 'update', 'patch', 'delete']
  - apiGroups: ['']
    resources: ['namespaces']
    verbs: ['get', 'list', 'watch', 'create', 'delete']
  - apiGroups: ['apps', 'extensions']
    resources: ['daemonsets', 'deployments']
    verbs: ['get', 'list', 'watch', 'create', 'update', 'patch', 'delete']
