name: CI Check
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'
jobs:
  ci-check:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Install dependencies
        run: yarn install --offline
      - name: Build project
        run: yarn build
      - name: Run Continuous Integration checks
        run: yarn ci-check
